### PR TITLE
Delete Blackgirl tech which doesn't exist anymore

### PR DESCRIPTION
**Pull request by Nirvikalpa108**

### CODE REVIEW

**Comment by JennyBrennan** [comment]
Could we swap this from deleting them to updating the URL to https://blackgirl.tech/ instead? They don't have meetups listed currently, but I know they're still active in the community so would be keen to keep them on here.

**Comment by Nirvikalpa108** [comment]
Hi @JennyBrennan, I agree it's a good idea to update the URL instead of completely deleting it!
What is the best practice to do this on GitHub?
Should I close this PR #9 with the meetup deleted and create a new PR updating the meetup URL?
In this case I tried to create a new commit to the same PR, but it says there's a conflict (I guess because I deleted the meetup and then tried to re-enter it). 
Would I really appreciate your advice! CodeNewbie moment! Thank you! 😃

**Comment by Nirvikalpa108** [comment]
Hi again (!!) so I tried to figure this out myself using this [GitHub Help article](https://help.github.com/articles/resolving-a-merge-conflict-on-github/). It taught me how to resolve a merge conflict by removing the conflict markers and writing the code I wanted. I hope I've done the right thing. If not, I would really appreciate your feedback. Sorry, I'm probably making your work more complicated, but I really appreciate your patience with me, thank you so much :two_hearts: :two_hearts:

**Comment by JennyBrennan** [comment]
This looks great! Well done on figuring out the merge conflict! You definitely are not making things more complicated and I'm always super happy to answer any questions you have. 

Only little feedback is would you be able to reorder these to make sure the entries are still in alphabetical order?

**Comment by Nirvikalpa108** [comment]
Hi @JennyBrennan, this PR was showing a merge conflict, which I've now resolved but I think this PR is outdated. I'm not sure what to do in this case, if it just needs to be closed/deleted? Please let me know what is best? Thank you very much and I appreciate your patience again!

**Pull request closed without merging**
