### PR TITLE
Move CodeBar to underrepresented groups section

### PR DESCRIPTION
**Pull request by Nirvikalpa108**
It currently sits in the beginners section, but CodeBar is specifically for underrepresented groups so given our conversation in #8, maybe best to put in the underrepresented groups section? Let me know what you think @JennyBrennan

### CODE REVIEW

**Comment by JennyBrennan** [comment]
Also I've realised it looks like there'll be a merge conflict - if you have any trouble resolving this let me know and I'm happy to help/answer any questions :)

**Comment by Nirvikalpa108** [comment]
Great, CodeBar is now in the underrepresented groups section. I will make sure everything is in alphabetical order. Thanks! 😃

**Comment by JennyBrennan** [comment]
Hey Amina - I've noticed this PR is effectively re-adding meetups like Code && Cake that you removed in your other patch. That's because when you started this PR, those meetups were still there.

To fix this, you'll want to do a rebase. This makes the starting commit (or "base") of your PR the latest version of master. It'll likely result in a merge conflict - but you know how to resolve those now!

To rebase:
- git checkout master
- git fetch (to get the latest version of master)
- git checkout your-branch
- git rebase master

There are more details in this article: https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase

The other option is to simply remove those entries again in an additional commit - which will work, but makes for a slightly strange history, so the more 'proper' way is to rebase (though I'm not too worried either way!).

**Comment by Nirvikalpa108** [comment]
Amazing! Thank you so much for this clear and concise instruction! I still need to learn how to use the terminal, so I'm super excited to do this and complete this rebase. Baby is in nursery tomorrow (Wednesday), so will have time then. Can't wait! Thank you x

**Comment by Nirvikalpa108** [comment]
Hi @JennyBrennan, I went through the steps you described. I hope I've done it correctly. Would you mind taking a look please? Thank you so much!

**Comment by JennyBrennan** [comment]
End result looks perfect to me! Thanks hugely!

**Comment by Nirvikalpa108** [comment]
Thanks @JennyBrennan. I struggled with the rebase! I'm sorry that I have so many commits that are unnecessary. If you have any feedback, I would really appreciate it.
One of the main takeaways for me is not to use GitHub anymore to make my PRs, but rather to make my changes locally and then push using Git. I'm very happy that you asking me to rebase prompted me to learn how to use the terminal and Git. Very exciting!!! Thank you!

**Pull request merged**
